__author__ = "Guilherme Castelao"
__email__ = "guilherme@castelao.net"

from .cnv import CNV, fCNV
from .exceptions import CNVError

# __all__ = ['CNV', 'fCNV']


from pkg_resources import get_distribution, DistributionNotFound

try:
    __version__ = get_distribution(__name__).version
except DistributionNotFound:
    try:
        from .version import version as __version__
    except ImportError:
        raise ImportError(
            "Failed to find (autogenerated) version.py. "
            "This might be because you are installing from GitHub's tarballs, "
            "use the PyPI ones."
        )
